apiVersion: v1
kind: ConfigMap
metadata:
  name: wb-orders-config
  namespace: wb-orders
data:
  LOG_LEVEL: info
  KAFKA_BROKERS: kafka.kafka.svc.cluster.local:9092
  KAFKA_ORDERS_CREATED_TOPIC: wb.orders.created
  KAFKA_STATUS_CHANGED_TOPIC: wb.orders.status-changed
  KAFKA_ORDERS_RETRY_TOPIC: wb.orders.created.retry
  KAFKA_ORDERS_DLQ_TOPIC: wb.orders.created.dlq
  KAFKA_CONSUMER_GROUP: wb-orders-worker-v1
  CONSUMER_NAME: wb-orders-worker-v1
  OUTBOX_WORKERS: "4"
  OUTBOX_BATCH_SIZE: "50"
  OUTBOX_LEASE_DURATION: 4m
  ORDER_WORKERS: "8"
  KAFKA_BATCH_SIZE: "16"
